# NumPy: Numerical Python
***

NumPy's main object is the homogeneous multidimensional array. A table of elements of the same type, indexed by a tuple of non-negative integers. 
In NumPy, dimensions are called axes. 

NumPy's array class is called `ndarray`. 
### `ndarray.ndim`
The number of axes (dimensions) of the array
### `ndarray.shape`
The dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with `n` rows and `m` columns, `shape` will be `(n,m)`. 
The length of the `shape` tuple is therefore the number of axes, `ndim`.
### `ndarray.size`
The total number of elements of the array. This is equal to the product of the elements of `shape`. 
### `ndarray.dtype` 
An object describinig the type of the elements in the array. 
### `ndarray.data`
The buffere containing the actual elements of the arrray.
NumPy arrays are indexable, so this attribute is rarely needed. 
### `ndarray.dtype`
Data types supported by NumPy array includes: 
- int64
- float64
- complex   

### `ndarray.arrange(size)`
Creates a new `ndarray` with length of `size`
### `ndarray.reshape(shape)`
Arranges a one dimensional array into the specified `shape`.
**Note** `ndarray` is immutable, and attempting to create and array and later reshape it won't work, instead the creation and reshaping should be done in one swoop like streams. Instead a copy is returned.

In [1]:
import numpy as np
import itertools as it
a = np.arange(15)
print(a.reshape(3,5))
a

b = np.arange(10).reshape(2,5)
c = np.array(range(2, 20, 2))

d = np.array([[1,2], [3,4]], dtype=complex)
np.array([[1,2], [3,4]], dtype=int)

t = 0,3,2,3,2
type(t)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


tuple

In [8]:
mList = list(range(3))
for p in it.permutations(mList):
    print(p)

(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)


In [11]:
M = np.arange(10)
print(M)

[0 1 2 3 4 5 6 7 8 9]
